# Generated by Django 5.2.16 on 2026-07-23 07:04

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


def create_existing_student_profiles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    StudentCollaborationProfile = apps.get_model(
        "accounts", "StudentCollaborationProfile"
    )
    profiles = [
        StudentCollaborationProfile(user_id=user_id)
        for user_id in User.objects.filter(role="STUDENT").values_list("id", flat=True)
    ]
    StudentCollaborationProfile.objects.bulk_create(profiles, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_skill',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='accounts_skill_name_ci_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StudentCollaborationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collaboration_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=7)),
                ('availability', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_studentcollaborationprofile',
            },
        ),
        migrations.CreateModel(
            name='StudentProfileSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='accounts.studentcollaborationprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_links', to='accounts.skill')),
            ],
            options={
                'db_table': 'accounts_studentprofileskill',
            },
        ),
        migrations.AddField(
            model_name='studentcollaborationprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', through='accounts.StudentProfileSkill', to='accounts.skill'),
        ),
        migrations.AddConstraint(
            model_name='studentprofileskill',
            constraint=models.UniqueConstraint(fields=('profile', 'skill'), name='accounts_profile_skill_uniq'),
        ),
        migrations.AddConstraint(
            model_name='studentcollaborationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('collaboration_mode__in', ['ONLINE', 'OFFLINE'])), name='accounts_profile_mode_valid'),
        ),
        migrations.RunPython(
            create_existing_student_profiles,
            migrations.RunPython.noop,
        ),
    ]
