# Generated by Django 5.2.16 on 2026-07-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_collaboration_profiles'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('NON_MEMBER', 'Non-member'), ('MEMBER', 'Member')], default='NON_MEMBER', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('membership_status__in', ['NON_MEMBER', 'MEMBER'])), name='accounts_user_membership_valid'),
        ),
    ]
