# Generated by Django 5.2.16 on 2026-07-15 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_materials', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='courses.coursesection')),
            ],
            options={
                'db_table': 'materials_material',
            },
        ),
        migrations.CreateModel(
            name='MaterialVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='materials.material')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'materials_materialversion',
                'ordering': ['material', 'version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['course', 'status', 'section', 'created_at'], name='material_course_feed_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialversion',
            constraint=models.UniqueConstraint(fields=('material', 'version_number'), name='material_version_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='material_version_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='materialversion',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='material_size_bytes_gt_0'),
        ),
    ]
