# Generated by Django 5.2.16 on 2026-07-15 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('syllabus', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('enrolment_mode', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='CLOSED', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses_course',
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='courses.course')),
            ],
            options={
                'db_table': 'courses_coursesection',
                'ordering': ['course', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=9)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses_enrolment',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'enrolment_mode'], name='course_status_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'status'], name='course_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='course_section_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='course_section_position_gte_1'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['student', 'status'], name='enrol_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['course', 'status'], name='enrol_course_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='course_student_enrolment_uniq'),
        ),
    ]
