# Generated by Django 5.2.16 on 2026-07-15 15:05

import apps.assignments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('due_at', models.DateTimeField()),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_upload_bytes', models.BigIntegerField(default=10485760)),
                ('allowed_extensions', models.JSONField(default=list, validators=[apps.assignments.models.validate_allowed_extensions])),
                ('allow_late_submissions', models.BooleanField(default=False)),
                ('allow_resubmission', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='courses.coursesection')),
            ],
            options={
                'db_table': 'assignments_assignment',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignments_submission',
            },
        ),
        migrations.CreateModel(
            name='SubmissionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('was_late', models.BooleanField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assignments.submission')),
            ],
            options={
                'db_table': 'assignments_submissionversion',
                'ordering': ['submission', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='GradeRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_revisions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_revisions', to='assignments.submission')),
                ('submission_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_revisions', to='assignments.submissionversion')),
            ],
            options={
                'db_table': 'assignments_graderevision',
                'ordering': ['submission', 'revision_number'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', 'status', 'due_at'], name='assignment_course_due_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'due_at'], name='assignment_status_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='assignment_max_score_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('max_upload_bytes__gt', 0)), name='assignment_max_upload_gt_0'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'created_at'], name='submission_student_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'created_at'], name='submission_assignment_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='assignment_student_submission_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submissionversion',
            constraint=models.UniqueConstraint(fields=('submission', 'version_number'), name='submission_version_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submissionversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='submission_version_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='submissionversion',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='submission_size_bytes_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='graderevision',
            constraint=models.UniqueConstraint(fields=('submission', 'revision_number'), name='grade_revision_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='graderevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='grade_revision_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='graderevision',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='grade_score_gte_0'),
        ),
    ]
