# Generated by Django 5.2.16 on 2026-07-15 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('COURSE_VIEWED', 'Course viewed'), ('MATERIAL_VIEWED', 'Material viewed'), ('MATERIAL_DOWNLOADED', 'Material downloaded'), ('ASSIGNMENT_VIEWED', 'Assignment viewed'), ('ANNOUNCEMENT_VIEWED', 'Announcement viewed'), ('SUBMISSION_CREATED', 'Submission created'), ('SUBMISSION_RESUBMITTED', 'Submission resubmitted')], max_length=32)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_activityevent',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['course', '-occurred_at'], name='activity_course_time_idx'), models.Index(fields=['course', 'user', '-occurred_at'], name='activity_course_user_idx'), models.Index(fields=['user', '-occurred_at'], name='activity_user_time_idx')],
            },
        ),
    ]
